### ISSUE TITLE
Create.php is different from the new create.php in sendy 1.1.9.5

### ISSUE THREAD

**Issue by jellevervloessem** [bown/Templates-for-Sendy#4]
When reinstalling this addon over the new sendy version, Is comptibility guaranteed???

**Comment by bown** [comment]
No, I haven't worked on moving it to a newer version, this is something I'm going to do with in the next update.

**Comment by bown** [comment]
Fixed issue in 1.0.3

**Comment by jellevervloessem** [comment]
works like a charm! Thanks.

> i see that the template_create is still with the redactor Wysiwyg....  (which is not a problem for creating templates)
