### ISSUE TITLE
Problem with templates after upgrade

### ISSUE THREAD

**Issue by jackyl69** [bown/Templates-for-Sendy#6]
Hi,

I've recently updated sendy and templates to latest version but it unfortunately doesn't fully work for me.
1. There is no editor present at all when creating new template - http://take.ms/lKpn3
2. When creating a new email from campaign, editor is also not visible and the button "Save and switch to html editor" doesn't work, clicking it does nothing. It works fine when I just create a new campaign using standard sendy option.

Any ideas what's wrong here?

Thanks,

Jack

**Comment by ElliotFriend** [comment]
I will say that I am experiencing the same issues.
1. I hadn't noticed this, all of our templates were already saved. However, my installation is reproducing the symptom.
2. I figured out a workaround for this:
   - Create a "New template campaign"
   - Click "Save & next"
   - Click "All campaigns" at the top of the sidebar menu
   - Click "Edit" next to the untitled campaign that you just created

After following those steps, I was able to edit the campaign like you would expect to.

**Comment by jackyl69** [comment]
Yes, that's how I was editing templates, but would love to have it working properly for my clients.

**Comment by ElliotFriend** [comment]
The difference I see in the developer's console in Chrome is one error on the template page: `Uncaught ReferenceError: CKEDITOR is not defined` which points to the file `yoursendyurl.com/js/create/editor.js?2:4`

**Comment by jackyl69** [comment]
Hi @ElliotFriend  

I am not a developer and first time using github, but I noticed you created another branch - https://github.com/ElliotFriend/Templates-for-Sendy/tree/ckeditor-not-invoked - should I just copy the amended files from this and the issue will be fixed?

Thanks,

Jack

**Comment by jackyl69** [comment]
Hi,

I've added those files and all works fine now, except for editing an existing template - there is just no CKeditor at all.

Also noticed in the templates.php file a bunch of JS relating to "redaktor" which I believe was the previous editor? Are these still needed there?

<script src="<?php echo get_app_info('path');?>/js/redactor/redactor.min.js?5"></script>

<script src="<?php echo get_app_info('path');?>/js/redactor/fontcolor.js?5"></script>

<script src="<?php echo get_app_info('path');?>/js/redactor/fontsize.js?5"></script>

<script src="<?php echo get_app_info('path');?>/js/redactor/fontfamily.js?5"></script>

<script src="<?php echo get_app_info('path');?>/js/redactor/personalizationtags.js?5"></script>

<link rel="stylesheet" href="<?php echo get_app_info('path');?>/js/redactor/redactor.css?5" />

**Comment by ElliotFriend** [comment]
@jackyl69 

Glad it was able to help you out (at least a little)! I missed the references in `templates.php`, so thank you for pointing those out.

As for editing the templates, I added the javascript to the `edit-template.php` file on the server that hosts our Sendy instance, but forgot to incorporate that change into my branch. I'm so sorry, but very glad you caught that! Feeling a little bit sheepish right now, :grimacing:

The updates are live on my branch, now and you should be able to copy/paste and/or merge the files into your own installation.

Thanks for your help, and do let me know if any other issues arise.
